/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type { SeedIngestion, SeedIngestionInterface } from "../SeedIngestion";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "epoch",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "seed",
        type: "bytes32",
      },
    ],
    name: "SeedUpdated",
    type: "event",
  },
  {
    inputs: [],
    name: "currentEpoch",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "currentSeed",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_l1Epoch",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "_beaconRand",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "_blockHash",
        type: "bytes32",
      },
    ],
    name: "updateSeed",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506103a0806100206000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c8063766718081461004657806382d0177c146100645780638322062614610080575b600080fd5b61004e61009e565b60405161005b9190610153565b60405180910390f35b61007e600480360381019061007991906101d5565b6100a4565b005b610088610134565b6040516100959190610237565b60405180910390f35b60015481565b468383836001546040516020016100bf959493929190610294565b60405160208183030381529060405280519060200120600081905550600160008154809291906100ee90610322565b91905055506001547fb185dcb9cc7608a6209934800eeccf71b8426846bbd3cf042c43d1fe2cf329ae6000546040516101279190610237565b60405180910390a2505050565b60005481565b6000819050919050565b61014d8161013a565b82525050565b60006020820190506101686000830184610144565b92915050565b600080fd5b61017c8161013a565b811461018757600080fd5b50565b60008135905061019981610173565b92915050565b6000819050919050565b6101b28161019f565b81146101bd57600080fd5b50565b6000813590506101cf816101a9565b92915050565b6000806000606084860312156101ee576101ed61016e565b5b60006101fc8682870161018a565b935050602061020d868287016101c0565b925050604061021e868287016101c0565b9150509250925092565b6102318161019f565b82525050565b600060208201905061024c6000830184610228565b92915050565b6000819050919050565b61026d6102688261013a565b610252565b82525050565b6000819050919050565b61028e6102898261019f565b610273565b82525050565b60006102a0828861025c565b6020820191506102b0828761025c565b6020820191506102c0828661027d565b6020820191506102d0828561027d565b6020820191506102e0828461025c565b6020820191508190509695505050505050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052601160045260246000fd5b600061032d8261013a565b91507fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff820361035f5761035e6102f3565b5b60018201905091905056fea2646970667358221220ada1489a15df6a4f535e86c6b04843d606e4c178127dd3dae85b6384bdc1f5e764736f6c63430008180033";

type SeedIngestionConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SeedIngestionConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class SeedIngestion__factory extends ContractFactory {
  constructor(...args: SeedIngestionConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      SeedIngestion & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): SeedIngestion__factory {
    return super.connect(runner) as SeedIngestion__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SeedIngestionInterface {
    return new Interface(_abi) as SeedIngestionInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): SeedIngestion {
    return new Contract(address, _abi, runner) as unknown as SeedIngestion;
  }
}
