/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface RegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "UNBONDING_PERIOD"
      | "activate"
      | "nodes"
      | "register"
      | "unbond"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Activated"
      | "Exited"
      | "Registered"
      | "UnbondingStarted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "UNBONDING_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "activate", values?: undefined): string;
  encodeFunctionData(functionFragment: "nodes", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "register", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "unbond", values?: undefined): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "UNBONDING_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "activate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nodes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unbond", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace ActivatedEvent {
  export type InputTuple = [node: AddressLike];
  export type OutputTuple = [node: string];
  export interface OutputObject {
    node: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExitedEvent {
  export type InputTuple = [node: AddressLike];
  export type OutputTuple = [node: string];
  export interface OutputObject {
    node: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RegisteredEvent {
  export type InputTuple = [node: AddressLike, stake: BigNumberish];
  export type OutputTuple = [node: string, stake: bigint];
  export interface OutputObject {
    node: string;
    stake: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnbondingStartedEvent {
  export type InputTuple = [node: AddressLike, releaseTime: BigNumberish];
  export type OutputTuple = [node: string, releaseTime: bigint];
  export interface OutputObject {
    node: string;
    releaseTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Registry extends BaseContract {
  connect(runner?: ContractRunner | null): Registry;
  waitForDeployment(): Promise<this>;

  interface: RegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  UNBONDING_PERIOD: TypedContractMethod<[], [bigint], "view">;

  activate: TypedContractMethod<[], [void], "nonpayable">;

  nodes: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, string, bigint] & {
        stake: bigint;
        age: bigint;
        state: bigint;
        vrfKey: string;
        unbondTime: bigint;
      }
    ],
    "view"
  >;

  register: TypedContractMethod<[_vrfKey: BytesLike], [void], "payable">;

  unbond: TypedContractMethod<[], [void], "nonpayable">;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "UNBONDING_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "activate"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "nodes"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, string, bigint] & {
        stake: bigint;
        age: bigint;
        state: bigint;
        vrfKey: string;
        unbondTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "register"
  ): TypedContractMethod<[_vrfKey: BytesLike], [void], "payable">;
  getFunction(
    nameOrSignature: "unbond"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "Activated"
  ): TypedContractEvent<
    ActivatedEvent.InputTuple,
    ActivatedEvent.OutputTuple,
    ActivatedEvent.OutputObject
  >;
  getEvent(
    key: "Exited"
  ): TypedContractEvent<
    ExitedEvent.InputTuple,
    ExitedEvent.OutputTuple,
    ExitedEvent.OutputObject
  >;
  getEvent(
    key: "Registered"
  ): TypedContractEvent<
    RegisteredEvent.InputTuple,
    RegisteredEvent.OutputTuple,
    RegisteredEvent.OutputObject
  >;
  getEvent(
    key: "UnbondingStarted"
  ): TypedContractEvent<
    UnbondingStartedEvent.InputTuple,
    UnbondingStartedEvent.OutputTuple,
    UnbondingStartedEvent.OutputObject
  >;

  filters: {
    "Activated(address)": TypedContractEvent<
      ActivatedEvent.InputTuple,
      ActivatedEvent.OutputTuple,
      ActivatedEvent.OutputObject
    >;
    Activated: TypedContractEvent<
      ActivatedEvent.InputTuple,
      ActivatedEvent.OutputTuple,
      ActivatedEvent.OutputObject
    >;

    "Exited(address)": TypedContractEvent<
      ExitedEvent.InputTuple,
      ExitedEvent.OutputTuple,
      ExitedEvent.OutputObject
    >;
    Exited: TypedContractEvent<
      ExitedEvent.InputTuple,
      ExitedEvent.OutputTuple,
      ExitedEvent.OutputObject
    >;

    "Registered(address,uint256)": TypedContractEvent<
      RegisteredEvent.InputTuple,
      RegisteredEvent.OutputTuple,
      RegisteredEvent.OutputObject
    >;
    Registered: TypedContractEvent<
      RegisteredEvent.InputTuple,
      RegisteredEvent.OutputTuple,
      RegisteredEvent.OutputObject
    >;

    "UnbondingStarted(address,uint256)": TypedContractEvent<
      UnbondingStartedEvent.InputTuple,
      UnbondingStartedEvent.OutputTuple,
      UnbondingStartedEvent.OutputObject
    >;
    UnbondingStarted: TypedContractEvent<
      UnbondingStartedEvent.InputTuple,
      UnbondingStartedEvent.OutputTuple,
      UnbondingStartedEvent.OutputObject
    >;
  };
}
