/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface SeedIngestionInterface extends Interface {
  getFunction(
    nameOrSignature: "currentEpoch" | "currentSeed" | "updateSeed"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "SeedUpdated"): EventFragment;

  encodeFunctionData(
    functionFragment: "currentEpoch",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentSeed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateSeed",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "currentEpoch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentSeed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "updateSeed", data: BytesLike): Result;
}

export namespace SeedUpdatedEvent {
  export type InputTuple = [epoch: BigNumberish, seed: BytesLike];
  export type OutputTuple = [epoch: bigint, seed: string];
  export interface OutputObject {
    epoch: bigint;
    seed: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SeedIngestion extends BaseContract {
  connect(runner?: ContractRunner | null): SeedIngestion;
  waitForDeployment(): Promise<this>;

  interface: SeedIngestionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  currentEpoch: TypedContractMethod<[], [bigint], "view">;

  currentSeed: TypedContractMethod<[], [string], "view">;

  updateSeed: TypedContractMethod<
    [_l1Epoch: BigNumberish, _beaconRand: BytesLike, _blockHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "currentEpoch"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "currentSeed"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "updateSeed"
  ): TypedContractMethod<
    [_l1Epoch: BigNumberish, _beaconRand: BytesLike, _blockHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "SeedUpdated"
  ): TypedContractEvent<
    SeedUpdatedEvent.InputTuple,
    SeedUpdatedEvent.OutputTuple,
    SeedUpdatedEvent.OutputObject
  >;

  filters: {
    "SeedUpdated(uint256,bytes32)": TypedContractEvent<
      SeedUpdatedEvent.InputTuple,
      SeedUpdatedEvent.OutputTuple,
      SeedUpdatedEvent.OutputObject
    >;
    SeedUpdated: TypedContractEvent<
      SeedUpdatedEvent.InputTuple,
      SeedUpdatedEvent.OutputTuple,
      SeedUpdatedEvent.OutputObject
    >;
  };
}
